//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team9_winxshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThanhToan
    {
        public int MaDH { get; set; }
        public int MaHTTT { get; set; }
        public int SoTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
    }
}
